Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Agencias 
	Inherits _Agencias
    Public Function EC_obtAgencia(ByVal sEIdAgencia As String) As String
        If LoadByPrimaryKey(sEIdAgencia) Then
            Return Me.Agencia
        Else
            Return False
        End If
    End Function
End Class
