Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Areas 
	Inherits _Areas
    Public Function obtCargo(ByVal sIdArea As String) As String
        Dim sArea As String

    End Function
End Class
