
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _BuzonInterno
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "BuzonInterno"
			Me.MappingName = "BuzonInterno"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_BuzonInternoLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal IdBuzonInterno As Integer) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_BuzonInterno.Parameters.IdBuzonInterno, IdBuzonInterno)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_BuzonInternoLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdBuzonInterno As SqlParameter
			Get
				Return New SqlParameter("@IdBuzonInterno", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdAsigDocInterno As SqlParameter
			Get
				Return New SqlParameter("@IdAsigDocInterno", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property FechaLlegada As SqlParameter
			Get
				Return New SqlParameter("@FechaLlegada", SqlDbType.DateTime, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property FechaLeido As SqlParameter
			Get
				Return New SqlParameter("@FechaLeido", SqlDbType.DateTime, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property FechaLimite As SqlParameter
			Get
				Return New SqlParameter("@FechaLimite", SqlDbType.DateTime, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdCondicionEnvio As SqlParameter
			Get
				Return New SqlParameter("@IdCondicionEnvio", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdEstBuzonInterno As SqlParameter
			Get
				Return New SqlParameter("@IdEstBuzonInterno", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property Observaciones As SqlParameter
			Get
				Return New SqlParameter("@Observaciones", SqlDbType.VarChar, 250)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdUserR As SqlParameter
			Get
				Return New SqlParameter("@IdUserR", SqlDbType.Char, 6)
			End Get
		End Property
		
		Public Shared ReadOnly Property FechaR As SqlParameter
			Get
				Return New SqlParameter("@FechaR", SqlDbType.DateTime, 0)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdBuzonInterno As String = "IdBuzonInterno"
        Public Const IdAsigDocInterno As String = "IdAsigDocInterno"
        Public Const FechaLlegada As String = "FechaLlegada"
        Public Const FechaLeido As String = "FechaLeido"
        Public Const FechaLimite As String = "FechaLimite"
        Public Const IdCondicionEnvio As String = "IdCondicionEnvio"
        Public Const IdEstBuzonInterno As String = "IdEstBuzonInterno"
        Public Const Observaciones As String = "Observaciones"
        Public Const IdUserR As String = "IdUserR"
        Public Const FechaR As String = "FechaR"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdBuzonInterno) = _BuzonInterno.PropertyNames.IdBuzonInterno
				ht(IdAsigDocInterno) = _BuzonInterno.PropertyNames.IdAsigDocInterno
				ht(FechaLlegada) = _BuzonInterno.PropertyNames.FechaLlegada
				ht(FechaLeido) = _BuzonInterno.PropertyNames.FechaLeido
				ht(FechaLimite) = _BuzonInterno.PropertyNames.FechaLimite
				ht(IdCondicionEnvio) = _BuzonInterno.PropertyNames.IdCondicionEnvio
				ht(IdEstBuzonInterno) = _BuzonInterno.PropertyNames.IdEstBuzonInterno
				ht(Observaciones) = _BuzonInterno.PropertyNames.Observaciones
				ht(IdUserR) = _BuzonInterno.PropertyNames.IdUserR
				ht(FechaR) = _BuzonInterno.PropertyNames.FechaR

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdBuzonInterno As String = "IdBuzonInterno"
        Public Const IdAsigDocInterno As String = "IdAsigDocInterno"
        Public Const FechaLlegada As String = "FechaLlegada"
        Public Const FechaLeido As String = "FechaLeido"
        Public Const FechaLimite As String = "FechaLimite"
        Public Const IdCondicionEnvio As String = "IdCondicionEnvio"
        Public Const IdEstBuzonInterno As String = "IdEstBuzonInterno"
        Public Const Observaciones As String = "Observaciones"
        Public Const IdUserR As String = "IdUserR"
        Public Const FechaR As String = "FechaR"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdBuzonInterno) = _BuzonInterno.ColumnNames.IdBuzonInterno
				ht(IdAsigDocInterno) = _BuzonInterno.ColumnNames.IdAsigDocInterno
				ht(FechaLlegada) = _BuzonInterno.ColumnNames.FechaLlegada
				ht(FechaLeido) = _BuzonInterno.ColumnNames.FechaLeido
				ht(FechaLimite) = _BuzonInterno.ColumnNames.FechaLimite
				ht(IdCondicionEnvio) = _BuzonInterno.ColumnNames.IdCondicionEnvio
				ht(IdEstBuzonInterno) = _BuzonInterno.ColumnNames.IdEstBuzonInterno
				ht(Observaciones) = _BuzonInterno.ColumnNames.Observaciones
				ht(IdUserR) = _BuzonInterno.ColumnNames.IdUserR
				ht(FechaR) = _BuzonInterno.ColumnNames.FechaR

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdBuzonInterno As String = "s_IdBuzonInterno"
        Public Const IdAsigDocInterno As String = "s_IdAsigDocInterno"
        Public Const FechaLlegada As String = "s_FechaLlegada"
        Public Const FechaLeido As String = "s_FechaLeido"
        Public Const FechaLimite As String = "s_FechaLimite"
        Public Const IdCondicionEnvio As String = "s_IdCondicionEnvio"
        Public Const IdEstBuzonInterno As String = "s_IdEstBuzonInterno"
        Public Const Observaciones As String = "s_Observaciones"
        Public Const IdUserR As String = "s_IdUserR"
        Public Const FechaR As String = "s_FechaR"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property IdBuzonInterno As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.IdBuzonInterno)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.IdBuzonInterno, Value)
			End Set
		End Property

		Public Overridable Property IdAsigDocInterno As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.IdAsigDocInterno)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.IdAsigDocInterno, Value)
			End Set
		End Property

		Public Overridable Property FechaLlegada As DateTime
			Get
				Return MyBase.GetDateTime(ColumnNames.FechaLlegada)
			End Get
			Set(ByVal Value As DateTime)
				MyBase.SetDateTime(ColumnNames.FechaLlegada, Value)
			End Set
		End Property

		Public Overridable Property FechaLeido As DateTime
			Get
				Return MyBase.GetDateTime(ColumnNames.FechaLeido)
			End Get
			Set(ByVal Value As DateTime)
				MyBase.SetDateTime(ColumnNames.FechaLeido, Value)
			End Set
		End Property

		Public Overridable Property FechaLimite As DateTime
			Get
				Return MyBase.GetDateTime(ColumnNames.FechaLimite)
			End Get
			Set(ByVal Value As DateTime)
				MyBase.SetDateTime(ColumnNames.FechaLimite, Value)
			End Set
		End Property

		Public Overridable Property IdCondicionEnvio As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.IdCondicionEnvio)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.IdCondicionEnvio, Value)
			End Set
		End Property

		Public Overridable Property IdEstBuzonInterno As Integer
			Get
				Return MyBase.GetInteger(ColumnNames.IdEstBuzonInterno)
			End Get
			Set(ByVal Value As Integer)
				MyBase.SetInteger(ColumnNames.IdEstBuzonInterno, Value)
			End Set
		End Property

		Public Overridable Property Observaciones As String
			Get
				Return MyBase.GetString(ColumnNames.Observaciones)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Observaciones, Value)
			End Set
		End Property

		Public Overridable Property IdUserR As String
			Get
				Return MyBase.GetString(ColumnNames.IdUserR)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.IdUserR, Value)
			End Set
		End Property

		Public Overridable Property FechaR As DateTime
			Get
				Return MyBase.GetDateTime(ColumnNames.FechaR)
			End Get
			Set(ByVal Value As DateTime)
				MyBase.SetDateTime(ColumnNames.FechaR, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdBuzonInterno As String
			Get
				If Me.IsColumnNull(ColumnNames.IdBuzonInterno) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.IdBuzonInterno)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdBuzonInterno)
				Else
					Me.IdBuzonInterno = MyBase.SetIntegerAsString(ColumnNames.IdBuzonInterno, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdAsigDocInterno As String
			Get
				If Me.IsColumnNull(ColumnNames.IdAsigDocInterno) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.IdAsigDocInterno)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdAsigDocInterno)
				Else
					Me.IdAsigDocInterno = MyBase.SetIntegerAsString(ColumnNames.IdAsigDocInterno, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaLlegada As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaLlegada) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaLlegada)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaLlegada)
				Else
					Me.FechaLlegada = MyBase.SetDateTimeAsString(ColumnNames.FechaLlegada, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaLeido As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaLeido) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaLeido)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaLeido)
				Else
					Me.FechaLeido = MyBase.SetDateTimeAsString(ColumnNames.FechaLeido, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaLimite As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaLimite) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaLimite)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaLimite)
				Else
					Me.FechaLimite = MyBase.SetDateTimeAsString(ColumnNames.FechaLimite, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdCondicionEnvio As String
			Get
				If Me.IsColumnNull(ColumnNames.IdCondicionEnvio) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.IdCondicionEnvio)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdCondicionEnvio)
				Else
					Me.IdCondicionEnvio = MyBase.SetIntegerAsString(ColumnNames.IdCondicionEnvio, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdEstBuzonInterno As String
			Get
				If Me.IsColumnNull(ColumnNames.IdEstBuzonInterno) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ColumnNames.IdEstBuzonInterno)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdEstBuzonInterno)
				Else
					Me.IdEstBuzonInterno = MyBase.SetIntegerAsString(ColumnNames.IdEstBuzonInterno, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Observaciones As String
			Get
				If Me.IsColumnNull(ColumnNames.Observaciones) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Observaciones)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Observaciones)
				Else
					Me.Observaciones = MyBase.SetStringAsString(ColumnNames.Observaciones, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdUserR As String
			Get
				If Me.IsColumnNull(ColumnNames.IdUserR) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.IdUserR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdUserR)
				Else
					Me.IdUserR = MyBase.SetStringAsString(ColumnNames.IdUserR, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaR As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaR) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaR)
				Else
					Me.FechaR = MyBase.SetDateTimeAsString(ColumnNames.FechaR, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdBuzonInterno() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdBuzonInterno, Parameters.IdBuzonInterno)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdAsigDocInterno() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdAsigDocInterno, Parameters.IdAsigDocInterno)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaLlegada() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaLlegada, Parameters.FechaLlegada)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaLeido() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaLeido, Parameters.FechaLeido)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaLimite() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaLimite, Parameters.FechaLimite)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdCondicionEnvio() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdCondicionEnvio, Parameters.IdCondicionEnvio)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdEstBuzonInterno() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdEstBuzonInterno, Parameters.IdEstBuzonInterno)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Observaciones() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Observaciones, Parameters.Observaciones)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdUserR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdUserR, Parameters.IdUserR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaR, Parameters.FechaR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdBuzonInterno() As WhereParameter 
			Get
				If _IdBuzonInterno_W Is Nothing Then
					_IdBuzonInterno_W = TearOff.IdBuzonInterno
				End If
				Return _IdBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property IdAsigDocInterno() As WhereParameter 
			Get
				If _IdAsigDocInterno_W Is Nothing Then
					_IdAsigDocInterno_W = TearOff.IdAsigDocInterno
				End If
				Return _IdAsigDocInterno_W
			End Get
		End Property

		Public ReadOnly Property FechaLlegada() As WhereParameter 
			Get
				If _FechaLlegada_W Is Nothing Then
					_FechaLlegada_W = TearOff.FechaLlegada
				End If
				Return _FechaLlegada_W
			End Get
		End Property

		Public ReadOnly Property FechaLeido() As WhereParameter 
			Get
				If _FechaLeido_W Is Nothing Then
					_FechaLeido_W = TearOff.FechaLeido
				End If
				Return _FechaLeido_W
			End Get
		End Property

		Public ReadOnly Property FechaLimite() As WhereParameter 
			Get
				If _FechaLimite_W Is Nothing Then
					_FechaLimite_W = TearOff.FechaLimite
				End If
				Return _FechaLimite_W
			End Get
		End Property

		Public ReadOnly Property IdCondicionEnvio() As WhereParameter 
			Get
				If _IdCondicionEnvio_W Is Nothing Then
					_IdCondicionEnvio_W = TearOff.IdCondicionEnvio
				End If
				Return _IdCondicionEnvio_W
			End Get
		End Property

		Public ReadOnly Property IdEstBuzonInterno() As WhereParameter 
			Get
				If _IdEstBuzonInterno_W Is Nothing Then
					_IdEstBuzonInterno_W = TearOff.IdEstBuzonInterno
				End If
				Return _IdEstBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property Observaciones() As WhereParameter 
			Get
				If _Observaciones_W Is Nothing Then
					_Observaciones_W = TearOff.Observaciones
				End If
				Return _Observaciones_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As WhereParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As WhereParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Private _IdBuzonInterno_W As WhereParameter = Nothing
		Private _IdAsigDocInterno_W As WhereParameter = Nothing
		Private _FechaLlegada_W As WhereParameter = Nothing
		Private _FechaLeido_W As WhereParameter = Nothing
		Private _FechaLimite_W As WhereParameter = Nothing
		Private _IdCondicionEnvio_W As WhereParameter = Nothing
		Private _IdEstBuzonInterno_W As WhereParameter = Nothing
		Private _Observaciones_W As WhereParameter = Nothing
		Private _IdUserR_W As WhereParameter = Nothing
		Private _FechaR_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdBuzonInterno_W = Nothing
			_IdAsigDocInterno_W = Nothing
			_FechaLlegada_W = Nothing
			_FechaLeido_W = Nothing
			_FechaLimite_W = Nothing
			_IdCondicionEnvio_W = Nothing
			_IdEstBuzonInterno_W = Nothing
			_Observaciones_W = Nothing
			_IdUserR_W = Nothing
			_FechaR_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdBuzonInterno() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdBuzonInterno, Parameters.IdBuzonInterno)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdAsigDocInterno() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdAsigDocInterno, Parameters.IdAsigDocInterno)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaLlegada() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaLlegada, Parameters.FechaLlegada)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaLeido() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaLeido, Parameters.FechaLeido)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaLimite() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaLimite, Parameters.FechaLimite)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdCondicionEnvio() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdCondicionEnvio, Parameters.IdCondicionEnvio)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdEstBuzonInterno() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdEstBuzonInterno, Parameters.IdEstBuzonInterno)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Observaciones() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Observaciones, Parameters.Observaciones)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdUserR, Parameters.IdUserR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaR, Parameters.FechaR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdBuzonInterno() As AggregateParameter 
			Get
				If _IdBuzonInterno_W Is Nothing Then
					_IdBuzonInterno_W = TearOff.IdBuzonInterno
				End If
				Return _IdBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property IdAsigDocInterno() As AggregateParameter 
			Get
				If _IdAsigDocInterno_W Is Nothing Then
					_IdAsigDocInterno_W = TearOff.IdAsigDocInterno
				End If
				Return _IdAsigDocInterno_W
			End Get
		End Property

		Public ReadOnly Property FechaLlegada() As AggregateParameter 
			Get
				If _FechaLlegada_W Is Nothing Then
					_FechaLlegada_W = TearOff.FechaLlegada
				End If
				Return _FechaLlegada_W
			End Get
		End Property

		Public ReadOnly Property FechaLeido() As AggregateParameter 
			Get
				If _FechaLeido_W Is Nothing Then
					_FechaLeido_W = TearOff.FechaLeido
				End If
				Return _FechaLeido_W
			End Get
		End Property

		Public ReadOnly Property FechaLimite() As AggregateParameter 
			Get
				If _FechaLimite_W Is Nothing Then
					_FechaLimite_W = TearOff.FechaLimite
				End If
				Return _FechaLimite_W
			End Get
		End Property

		Public ReadOnly Property IdCondicionEnvio() As AggregateParameter 
			Get
				If _IdCondicionEnvio_W Is Nothing Then
					_IdCondicionEnvio_W = TearOff.IdCondicionEnvio
				End If
				Return _IdCondicionEnvio_W
			End Get
		End Property

		Public ReadOnly Property IdEstBuzonInterno() As AggregateParameter 
			Get
				If _IdEstBuzonInterno_W Is Nothing Then
					_IdEstBuzonInterno_W = TearOff.IdEstBuzonInterno
				End If
				Return _IdEstBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property Observaciones() As AggregateParameter 
			Get
				If _Observaciones_W Is Nothing Then
					_Observaciones_W = TearOff.Observaciones
				End If
				Return _Observaciones_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Private _IdBuzonInterno_W As AggregateParameter = Nothing
		Private _IdAsigDocInterno_W As AggregateParameter = Nothing
		Private _FechaLlegada_W As AggregateParameter = Nothing
		Private _FechaLeido_W As AggregateParameter = Nothing
		Private _FechaLimite_W As AggregateParameter = Nothing
		Private _IdCondicionEnvio_W As AggregateParameter = Nothing
		Private _IdEstBuzonInterno_W As AggregateParameter = Nothing
		Private _Observaciones_W As AggregateParameter = Nothing
		Private _IdUserR_W As AggregateParameter = Nothing
		Private _FechaR_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdBuzonInterno_W = Nothing
		_IdAsigDocInterno_W = Nothing
		_FechaLlegada_W = Nothing
		_FechaLeido_W = Nothing
		_FechaLimite_W = Nothing
		_IdCondicionEnvio_W = Nothing
		_IdEstBuzonInterno_W = Nothing
		_Observaciones_W = Nothing
		_IdUserR_W = Nothing
		_FechaR_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_BuzonInternoInsert]" 
	    
		CreateParameters(cmd)
		
		Dim p As SqlParameter
		p = cmd.Parameters(Parameters.IdBuzonInterno.ParameterName)
		p.Direction = ParameterDirection.Output
    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_BuzonInternoUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_BuzonInternoDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdBuzonInterno)
		p.SourceColumn = ColumnNames.IdBuzonInterno
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdBuzonInterno)
		p.SourceColumn = ColumnNames.IdBuzonInterno
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdAsigDocInterno)
		p.SourceColumn = ColumnNames.IdAsigDocInterno
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaLlegada)
		p.SourceColumn = ColumnNames.FechaLlegada
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaLeido)
		p.SourceColumn = ColumnNames.FechaLeido
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaLimite)
		p.SourceColumn = ColumnNames.FechaLimite
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdCondicionEnvio)
		p.SourceColumn = ColumnNames.IdCondicionEnvio
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdEstBuzonInterno)
		p.SourceColumn = ColumnNames.IdEstBuzonInterno
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Observaciones)
		p.SourceColumn = ColumnNames.Observaciones
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdUserR)
		p.SourceColumn = ColumnNames.IdUserR
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaR)
		p.SourceColumn = ColumnNames.FechaR
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

