
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.9)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _CARGOSXAREAXAGENCIA
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "CARGOSXAREAXAGENCIA"
			Me.MappingName = "CARGOSXAREAXAGENCIA"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_CARGOSXAREAXAGENCIALoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal IdCargo As string, ByVal IdArea As string, ByVal IdAgencia As string) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_CARGOSXAREAXAGENCIA.Parameters.IdCargo, IdCargo)

parameters.Add(_CARGOSXAREAXAGENCIA.Parameters.IdArea, IdArea)

parameters.Add(_CARGOSXAREAXAGENCIA.Parameters.IdAgencia, IdAgencia)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_CARGOSXAREAXAGENCIALoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdCargo As SqlParameter
			Get
				Return New SqlParameter("@IdCargo", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdArea As SqlParameter
			Get
				Return New SqlParameter("@IdArea", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdAgencia As SqlParameter
			Get
				Return New SqlParameter("@IdAgencia", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property Denominacion As SqlParameter
			Get
				Return New SqlParameter("@Denominacion", SqlDbType.VarChar, 40)
			End Get
		End Property
		
		Public Shared ReadOnly Property Activo As SqlParameter
			Get
				Return New SqlParameter("@Activo", SqlDbType.Char, 1)
			End Get
		End Property
		
		Public Shared ReadOnly Property Aportes As SqlParameter
			Get
				Return New SqlParameter("@Aportes", SqlDbType.Char, 1)
			End Get
		End Property
		
		Public Shared ReadOnly Property Ahorros As SqlParameter
			Get
				Return New SqlParameter("@Ahorros", SqlDbType.Char, 1)
			End Get
		End Property
		
		Public Shared ReadOnly Property Creditos As SqlParameter
			Get
				Return New SqlParameter("@Creditos", SqlDbType.Char, 1)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdCargo As String = "IdCargo"
        Public Const IdArea As String = "IdArea"
        Public Const IdAgencia As String = "IdAgencia"
        Public Const Denominacion As String = "Denominacion"
        Public Const Activo As String = "Activo"
        Public Const Aportes As String = "Aportes"
        Public Const Ahorros As String = "Ahorros"
        Public Const Creditos As String = "Creditos"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdCargo) = _CARGOSXAREAXAGENCIA.PropertyNames.IdCargo
				ht(IdArea) = _CARGOSXAREAXAGENCIA.PropertyNames.IdArea
				ht(IdAgencia) = _CARGOSXAREAXAGENCIA.PropertyNames.IdAgencia
				ht(Denominacion) = _CARGOSXAREAXAGENCIA.PropertyNames.Denominacion
				ht(Activo) = _CARGOSXAREAXAGENCIA.PropertyNames.Activo
				ht(Aportes) = _CARGOSXAREAXAGENCIA.PropertyNames.Aportes
				ht(Ahorros) = _CARGOSXAREAXAGENCIA.PropertyNames.Ahorros
				ht(Creditos) = _CARGOSXAREAXAGENCIA.PropertyNames.Creditos

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdCargo As String = "IdCargo"
        Public Const IdArea As String = "IdArea"
        Public Const IdAgencia As String = "IdAgencia"
        Public Const Denominacion As String = "Denominacion"
        Public Const Activo As String = "Activo"
        Public Const Aportes As String = "Aportes"
        Public Const Ahorros As String = "Ahorros"
        Public Const Creditos As String = "Creditos"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdCargo) = _CARGOSXAREAXAGENCIA.ColumnNames.IdCargo
				ht(IdArea) = _CARGOSXAREAXAGENCIA.ColumnNames.IdArea
				ht(IdAgencia) = _CARGOSXAREAXAGENCIA.ColumnNames.IdAgencia
				ht(Denominacion) = _CARGOSXAREAXAGENCIA.ColumnNames.Denominacion
				ht(Activo) = _CARGOSXAREAXAGENCIA.ColumnNames.Activo
				ht(Aportes) = _CARGOSXAREAXAGENCIA.ColumnNames.Aportes
				ht(Ahorros) = _CARGOSXAREAXAGENCIA.ColumnNames.Ahorros
				ht(Creditos) = _CARGOSXAREAXAGENCIA.ColumnNames.Creditos

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdCargo As String = "s_IdCargo"
        Public Const IdArea As String = "s_IdArea"
        Public Const IdAgencia As String = "s_IdAgencia"
        Public Const Denominacion As String = "s_Denominacion"
        Public Const Activo As String = "s_Activo"
        Public Const Aportes As String = "s_Aportes"
        Public Const Ahorros As String = "s_Ahorros"
        Public Const Creditos As String = "s_Creditos"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property IdCargo As string
			Get
				Return MyBase.Getstring(ColumnNames.IdCargo)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdCargo, Value)
			End Set
		End Property

		Public Overridable Property IdArea As string
			Get
				Return MyBase.Getstring(ColumnNames.IdArea)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdArea, Value)
			End Set
		End Property

		Public Overridable Property IdAgencia As string
			Get
				Return MyBase.Getstring(ColumnNames.IdAgencia)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdAgencia, Value)
			End Set
		End Property

		Public Overridable Property Denominacion As string
			Get
				Return MyBase.Getstring(ColumnNames.Denominacion)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Denominacion, Value)
			End Set
		End Property

		Public Overridable Property Activo As string
			Get
				Return MyBase.Getstring(ColumnNames.Activo)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Activo, Value)
			End Set
		End Property

		Public Overridable Property Aportes As string
			Get
				Return MyBase.Getstring(ColumnNames.Aportes)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Aportes, Value)
			End Set
		End Property

		Public Overridable Property Ahorros As string
			Get
				Return MyBase.Getstring(ColumnNames.Ahorros)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Ahorros, Value)
			End Set
		End Property

		Public Overridable Property Creditos As string
			Get
				Return MyBase.Getstring(ColumnNames.Creditos)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Creditos, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdCargo As String
			Get
				If Me.IsColumnNull(ColumnNames.IdCargo) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdCargo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdCargo)
				Else
					Me.IdCargo = MyBase.SetstringAsString(ColumnNames.IdCargo, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdArea As String
			Get
				If Me.IsColumnNull(ColumnNames.IdArea) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdArea)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdArea)
				Else
					Me.IdArea = MyBase.SetstringAsString(ColumnNames.IdArea, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdAgencia As String
			Get
				If Me.IsColumnNull(ColumnNames.IdAgencia) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdAgencia)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdAgencia)
				Else
					Me.IdAgencia = MyBase.SetstringAsString(ColumnNames.IdAgencia, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Denominacion As String
			Get
				If Me.IsColumnNull(ColumnNames.Denominacion) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Denominacion)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Denominacion)
				Else
					Me.Denominacion = MyBase.SetstringAsString(ColumnNames.Denominacion, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Activo As String
			Get
				If Me.IsColumnNull(ColumnNames.Activo) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Activo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Activo)
				Else
					Me.Activo = MyBase.SetstringAsString(ColumnNames.Activo, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Aportes As String
			Get
				If Me.IsColumnNull(ColumnNames.Aportes) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Aportes)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Aportes)
				Else
					Me.Aportes = MyBase.SetstringAsString(ColumnNames.Aportes, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Ahorros As String
			Get
				If Me.IsColumnNull(ColumnNames.Ahorros) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Ahorros)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Ahorros)
				Else
					Me.Ahorros = MyBase.SetstringAsString(ColumnNames.Ahorros, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Creditos As String
			Get
				If Me.IsColumnNull(ColumnNames.Creditos) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Creditos)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Creditos)
				Else
					Me.Creditos = MyBase.SetstringAsString(ColumnNames.Creditos, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdCargo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdCargo, Parameters.IdCargo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdArea() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdArea, Parameters.IdArea)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdAgencia() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdAgencia, Parameters.IdAgencia)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Denominacion() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Denominacion, Parameters.Denominacion)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Activo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Activo, Parameters.Activo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Aportes() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Aportes, Parameters.Aportes)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Ahorros() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Ahorros, Parameters.Ahorros)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Creditos() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Creditos, Parameters.Creditos)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdCargo() As WhereParameter 
			Get
				If _IdCargo_W Is Nothing Then
					_IdCargo_W = TearOff.IdCargo
				End If
				Return _IdCargo_W
			End Get
		End Property

		Public ReadOnly Property IdArea() As WhereParameter 
			Get
				If _IdArea_W Is Nothing Then
					_IdArea_W = TearOff.IdArea
				End If
				Return _IdArea_W
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As WhereParameter 
			Get
				If _IdAgencia_W Is Nothing Then
					_IdAgencia_W = TearOff.IdAgencia
				End If
				Return _IdAgencia_W
			End Get
		End Property

		Public ReadOnly Property Denominacion() As WhereParameter 
			Get
				If _Denominacion_W Is Nothing Then
					_Denominacion_W = TearOff.Denominacion
				End If
				Return _Denominacion_W
			End Get
		End Property

		Public ReadOnly Property Activo() As WhereParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Public ReadOnly Property Aportes() As WhereParameter 
			Get
				If _Aportes_W Is Nothing Then
					_Aportes_W = TearOff.Aportes
				End If
				Return _Aportes_W
			End Get
		End Property

		Public ReadOnly Property Ahorros() As WhereParameter 
			Get
				If _Ahorros_W Is Nothing Then
					_Ahorros_W = TearOff.Ahorros
				End If
				Return _Ahorros_W
			End Get
		End Property

		Public ReadOnly Property Creditos() As WhereParameter 
			Get
				If _Creditos_W Is Nothing Then
					_Creditos_W = TearOff.Creditos
				End If
				Return _Creditos_W
			End Get
		End Property

		Private _IdCargo_W As WhereParameter = Nothing
		Private _IdArea_W As WhereParameter = Nothing
		Private _IdAgencia_W As WhereParameter = Nothing
		Private _Denominacion_W As WhereParameter = Nothing
		Private _Activo_W As WhereParameter = Nothing
		Private _Aportes_W As WhereParameter = Nothing
		Private _Ahorros_W As WhereParameter = Nothing
		Private _Creditos_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdCargo_W = Nothing
			_IdArea_W = Nothing
			_IdAgencia_W = Nothing
			_Denominacion_W = Nothing
			_Activo_W = Nothing
			_Aportes_W = Nothing
			_Ahorros_W = Nothing
			_Creditos_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdCargo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdCargo, Parameters.IdCargo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdArea() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdArea, Parameters.IdArea)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdAgencia, Parameters.IdAgencia)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Denominacion() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Denominacion, Parameters.Denominacion)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Activo, Parameters.Activo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Aportes() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Aportes, Parameters.Aportes)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Ahorros() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Ahorros, Parameters.Ahorros)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Creditos() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Creditos, Parameters.Creditos)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdCargo() As AggregateParameter 
			Get
				If _IdCargo_W Is Nothing Then
					_IdCargo_W = TearOff.IdCargo
				End If
				Return _IdCargo_W
			End Get
		End Property

		Public ReadOnly Property IdArea() As AggregateParameter 
			Get
				If _IdArea_W Is Nothing Then
					_IdArea_W = TearOff.IdArea
				End If
				Return _IdArea_W
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As AggregateParameter 
			Get
				If _IdAgencia_W Is Nothing Then
					_IdAgencia_W = TearOff.IdAgencia
				End If
				Return _IdAgencia_W
			End Get
		End Property

		Public ReadOnly Property Denominacion() As AggregateParameter 
			Get
				If _Denominacion_W Is Nothing Then
					_Denominacion_W = TearOff.Denominacion
				End If
				Return _Denominacion_W
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Public ReadOnly Property Aportes() As AggregateParameter 
			Get
				If _Aportes_W Is Nothing Then
					_Aportes_W = TearOff.Aportes
				End If
				Return _Aportes_W
			End Get
		End Property

		Public ReadOnly Property Ahorros() As AggregateParameter 
			Get
				If _Ahorros_W Is Nothing Then
					_Ahorros_W = TearOff.Ahorros
				End If
				Return _Ahorros_W
			End Get
		End Property

		Public ReadOnly Property Creditos() As AggregateParameter 
			Get
				If _Creditos_W Is Nothing Then
					_Creditos_W = TearOff.Creditos
				End If
				Return _Creditos_W
			End Get
		End Property

		Private _IdCargo_W As AggregateParameter = Nothing
		Private _IdArea_W As AggregateParameter = Nothing
		Private _IdAgencia_W As AggregateParameter = Nothing
		Private _Denominacion_W As AggregateParameter = Nothing
		Private _Activo_W As AggregateParameter = Nothing
		Private _Aportes_W As AggregateParameter = Nothing
		Private _Ahorros_W As AggregateParameter = Nothing
		Private _Creditos_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdCargo_W = Nothing
		_IdArea_W = Nothing
		_IdAgencia_W = Nothing
		_Denominacion_W = Nothing
		_Activo_W = Nothing
		_Aportes_W = Nothing
		_Ahorros_W = Nothing
		_Creditos_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CARGOSXAREAXAGENCIAInsert]" 
	    
		CreateParameters(cmd)
		    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CARGOSXAREAXAGENCIAUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CARGOSXAREAXAGENCIADelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdCargo)
		p.SourceColumn = ColumnNames.IdCargo
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdArea)
		p.SourceColumn = ColumnNames.IdArea
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdAgencia)
		p.SourceColumn = ColumnNames.IdAgencia
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdCargo)
		p.SourceColumn = ColumnNames.IdCargo
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdArea)
		p.SourceColumn = ColumnNames.IdArea
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdAgencia)
		p.SourceColumn = ColumnNames.IdAgencia
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Denominacion)
		p.SourceColumn = ColumnNames.Denominacion
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Activo)
		p.SourceColumn = ColumnNames.Activo
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Aportes)
		p.SourceColumn = ColumnNames.Aportes
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Ahorros)
		p.SourceColumn = ColumnNames.Ahorros
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Creditos)
		p.SourceColumn = ColumnNames.Creditos
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

