Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Cargos 
    Inherits _Cargos
    Dim sECNomCargo As String
    Private dtCargos As DataTable
    Public Property lstCargos() As DataTable
        Get
            Return dtCargos
        End Get
        Set(ByVal value As DataTable)
            dtCargos = value
        End Set
    End Property
    Public Function EC_obtCargo(ByVal sEIdCargo As String) As String
        If EobtCargo(sEIdCargo) Then
            Return Me.Cargo
        Else
            Return " "
        End If
    End Function
    Public Function EC_ListaCargo() As Boolean
        If LoadAll() Then
            dtCargos = Me.DataTable
            Return True
        Else
            Return False
        End If
    End Function
End Class
