
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _Cargos
	Inherits SqlClientEntity
    Public Sub New()
        Me.QuerySource = "Cargos"
        Me.MappingName = "Cargos"
    End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_CargosLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal IdCargo As String) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_Cargos.Parameters.IdCargo, IdCargo)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_CargosLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdCargo As SqlParameter
			Get
				Return New SqlParameter("@IdCargo", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property Cargo As SqlParameter
			Get
				Return New SqlParameter("@Cargo", SqlDbType.VarChar, 40)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdCargo As String = "IdCargo"
        Public Const Cargo As String = "Cargo"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdCargo) = _Cargos.PropertyNames.IdCargo
				ht(Cargo) = _Cargos.PropertyNames.Cargo

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdCargo As String = "IdCargo"
        Public Const Cargo As String = "Cargo"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdCargo) = _Cargos.ColumnNames.IdCargo
				ht(Cargo) = _Cargos.ColumnNames.Cargo

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdCargo As String = "s_IdCargo"
        Public Const Cargo As String = "s_Cargo"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property IdCargo As String
			Get
				Return MyBase.GetString(ColumnNames.IdCargo)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.IdCargo, Value)
			End Set
		End Property

		Public Overridable Property Cargo As String
			Get
				Return MyBase.GetString(ColumnNames.Cargo)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Cargo, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdCargo As String
			Get
				If Me.IsColumnNull(ColumnNames.IdCargo) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.IdCargo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdCargo)
				Else
					Me.IdCargo = MyBase.SetStringAsString(ColumnNames.IdCargo, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Cargo As String
			Get
				If Me.IsColumnNull(ColumnNames.Cargo) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Cargo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Cargo)
				Else
					Me.Cargo = MyBase.SetStringAsString(ColumnNames.Cargo, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdCargo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdCargo, Parameters.IdCargo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Cargo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Cargo, Parameters.Cargo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdCargo() As WhereParameter 
			Get
				If _IdCargo_W Is Nothing Then
					_IdCargo_W = TearOff.IdCargo
				End If
				Return _IdCargo_W
			End Get
		End Property

		Public ReadOnly Property Cargo() As WhereParameter 
			Get
				If _Cargo_W Is Nothing Then
					_Cargo_W = TearOff.Cargo
				End If
				Return _Cargo_W
			End Get
		End Property

		Private _IdCargo_W As WhereParameter = Nothing
		Private _Cargo_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdCargo_W = Nothing
			_Cargo_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdCargo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdCargo, Parameters.IdCargo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Cargo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Cargo, Parameters.Cargo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdCargo() As AggregateParameter 
			Get
				If _IdCargo_W Is Nothing Then
					_IdCargo_W = TearOff.IdCargo
				End If
				Return _IdCargo_W
			End Get
		End Property

		Public ReadOnly Property Cargo() As AggregateParameter 
			Get
				If _Cargo_W Is Nothing Then
					_Cargo_W = TearOff.Cargo
				End If
				Return _Cargo_W
			End Get
		End Property

		Private _IdCargo_W As AggregateParameter = Nothing
		Private _Cargo_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdCargo_W = Nothing
		_Cargo_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CargosInsert]" 
	    
		CreateParameters(cmd)
		    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CargosUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_CargosDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdCargo)
		p.SourceColumn = ColumnNames.IdCargo
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdCargo)
		p.SourceColumn = ColumnNames.IdCargo
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Cargo)
		p.SourceColumn = ColumnNames.Cargo
		p.SourceVersion = DataRowVersion.Current


	End Sub	
    Public Function EobtCargo(ByVal sIdCargo As String) As Boolean
        Me.Where.IdCargo.Value = sIdCargo
        Me.Where.IdCargo.Operator = WhereParameter.Operand.Equal
        If Not (Me.Query.Load) Then
            Return False
        Else
            Return True
        End If
    End Function
End Class

