Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.3)

Public Class DocumentoInterno 
	Inherits _DocumentoInterno

    Public Function EC_insertaDocInt(ByVal sNroDoc As String, ByVal sIdTipoDocumento As Integer, ByVal sIdArea As String, _
                                     ByVal sIdAgencia As String, ByVal sPeriodo As String, ByVal sAsunto As String, _
                                     ByVal sEncabezado As String, ByVal sPrioridad As String, ByVal sFechaR As String, _
                                     ByVal sIdUserR As String) As Boolean
        AddNew()
        IdTipoDocumento = sIdTipoDocumento
        NroDoc = sNroDoc
        IdArea = sIdArea
        IdAgencia = sIdAgencia
        Periodo = sPeriodo
        Asunto = sAsunto
        Encabezado = sEncabezado
        Prioridad = sPrioridad
        FechaR = sFechaR
        IdUserR = sIdUserR
        Save()
    End Function


End Class
