
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.9)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _EstadoBuzonInterno
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "EstadoBuzonInterno"
			Me.MappingName = "EstadoBuzonInterno"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_EstadoBuzonInternoLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
    Public Overridable Function LoadByPrimaryKey(ByVal IdEstBuzonInterno As Integer) As Boolean

        Dim parameters As ListDictionary = New ListDictionary()
        parameters.Add(_EstadoBuzonInterno.Parameters.IdEstBuzonInterno, IdEstBuzonInterno)


        Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_EstadoBuzonInternoLoadByPrimaryKey]", parameters)

    End Function

#Region "Parameters"
    Protected Class Parameters

        Public Shared ReadOnly Property IdEstBuzonInterno() As SqlParameter
            Get
                Return New SqlParameter("@IdEstBuzonInterno", SqlDbType.Int, 0)
            End Get
        End Property

        Public Shared ReadOnly Property Estado() As SqlParameter
            Get
                Return New SqlParameter("@Estado", SqlDbType.VarChar, 15)
            End Get
        End Property

        Public Shared ReadOnly Property FechaR() As SqlParameter
            Get
                Return New SqlParameter("@FechaR", SqlDbType.DateTime, 0)
            End Get
        End Property

        Public Shared ReadOnly Property IdUserR() As SqlParameter
            Get
                Return New SqlParameter("@IdUserR", SqlDbType.Char, 6)
            End Get
        End Property

        Public Shared ReadOnly Property Activo() As SqlParameter
            Get
                Return New SqlParameter("@Activo", SqlDbType.Char, 1)
            End Get
        End Property

    End Class
#End Region

#Region "ColumnNames"
    Public Class ColumnNames

        Public Const IdEstBuzonInterno As String = "IdEstBuzonInterno"
        Public Const Estado As String = "Estado"
        Public Const FechaR As String = "FechaR"
        Public Const IdUserR As String = "IdUserR"
        Public Const Activo As String = "Activo"

        Public Shared Function ToPropertyName(ByVal columnName As String) As String

            If ht Is Nothing Then

                ht = New Hashtable

                ht(IdEstBuzonInterno) = _EstadoBuzonInterno.PropertyNames.IdEstBuzonInterno
                ht(Estado) = _EstadoBuzonInterno.PropertyNames.Estado
                ht(FechaR) = _EstadoBuzonInterno.PropertyNames.FechaR
                ht(IdUserR) = _EstadoBuzonInterno.PropertyNames.IdUserR
                ht(Activo) = _EstadoBuzonInterno.PropertyNames.Activo

            End If

            Return CType(ht(columnName), String)

        End Function

        Private Shared ht As Hashtable = Nothing
    End Class
#End Region

#Region "PropertyNames"
    Public Class PropertyNames

        Public Const IdEstBuzonInterno As String = "IdEstBuzonInterno"
        Public Const Estado As String = "Estado"
        Public Const FechaR As String = "FechaR"
        Public Const IdUserR As String = "IdUserR"
        Public Const Activo As String = "Activo"

        Public Shared Function ToColumnName(ByVal propertyName As String) As String

            If ht Is Nothing Then

                ht = New Hashtable

                ht(IdEstBuzonInterno) = _EstadoBuzonInterno.ColumnNames.IdEstBuzonInterno
                ht(Estado) = _EstadoBuzonInterno.ColumnNames.Estado
                ht(FechaR) = _EstadoBuzonInterno.ColumnNames.FechaR
                ht(IdUserR) = _EstadoBuzonInterno.ColumnNames.IdUserR
                ht(Activo) = _EstadoBuzonInterno.ColumnNames.Activo

            End If

            Return CType(ht(propertyName), String)

        End Function

        Private Shared ht As Hashtable = Nothing

    End Class
#End Region

#Region "StringPropertyNames"
    Public Class StringPropertyNames

        Public Const IdEstBuzonInterno As String = "s_IdEstBuzonInterno"
        Public Const Estado As String = "s_Estado"
        Public Const FechaR As String = "s_FechaR"
        Public Const IdUserR As String = "s_IdUserR"
        Public Const Activo As String = "s_Activo"

    End Class
#End Region

#Region "Properties"
    Public Overridable Property IdEstBuzonInterno() As Integer
        Get
            Return MyBase.GetInteger(ColumnNames.IdEstBuzonInterno)
        End Get
        Set(ByVal Value As Integer)
            MyBase.SetInteger(ColumnNames.IdEstBuzonInterno, Value)
        End Set
    End Property

    Public Overridable Property Estado() As String
        Get
            Return MyBase.GetString(ColumnNames.Estado)
        End Get
        Set(ByVal Value As String)
            MyBase.SetString(ColumnNames.Estado, Value)
        End Set
    End Property

    Public Overridable Property FechaR() As DateTime
        Get
            Return MyBase.GetDateTime(ColumnNames.FechaR)
        End Get
        Set(ByVal Value As DateTime)
            MyBase.SetDateTime(ColumnNames.FechaR, Value)
        End Set
    End Property

    Public Overridable Property IdUserR() As String
        Get
            Return MyBase.GetString(ColumnNames.IdUserR)
        End Get
        Set(ByVal Value As String)
            MyBase.SetString(ColumnNames.IdUserR, Value)
        End Set
    End Property

    Public Overridable Property Activo() As String
        Get
            Return MyBase.GetString(ColumnNames.Activo)
        End Get
        Set(ByVal Value As String)
            MyBase.SetString(ColumnNames.Activo, Value)
        End Set
    End Property


#End Region
	
	#Region "String Properties" 

		Public Overridable Property s_IdEstBuzonInterno As String
			Get
				If Me.IsColumnNull(ColumnNames.IdEstBuzonInterno) Then
					Return String.Empty
				Else
                Return MyBase.GetIntegerAsString(ColumnNames.IdEstBuzonInterno)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdEstBuzonInterno)
				Else
                Me.IdEstBuzonInterno = MyBase.SetIntegerAsString(ColumnNames.IdEstBuzonInterno, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Estado As String
			Get
				If Me.IsColumnNull(ColumnNames.Estado) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Estado)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Estado)
				Else
					Me.Estado = MyBase.SetstringAsString(ColumnNames.Estado, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaR As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaR) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaR)
				Else
					Me.FechaR = MyBase.SetDateTimeAsString(ColumnNames.FechaR, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdUserR As String
			Get
				If Me.IsColumnNull(ColumnNames.IdUserR) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdUserR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdUserR)
				Else
					Me.IdUserR = MyBase.SetstringAsString(ColumnNames.IdUserR, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Activo As String
			Get
				If Me.IsColumnNull(ColumnNames.Activo) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Activo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Activo)
				Else
					Me.Activo = MyBase.SetstringAsString(ColumnNames.Activo, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdEstBuzonInterno() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdEstBuzonInterno, Parameters.IdEstBuzonInterno)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Estado() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Estado, Parameters.Estado)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaR, Parameters.FechaR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdUserR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdUserR, Parameters.IdUserR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Activo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Activo, Parameters.Activo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdEstBuzonInterno() As WhereParameter 
			Get
				If _IdEstBuzonInterno_W Is Nothing Then
					_IdEstBuzonInterno_W = TearOff.IdEstBuzonInterno
				End If
				Return _IdEstBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property Estado() As WhereParameter 
			Get
				If _Estado_W Is Nothing Then
					_Estado_W = TearOff.Estado
				End If
				Return _Estado_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As WhereParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As WhereParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property Activo() As WhereParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Private _IdEstBuzonInterno_W As WhereParameter = Nothing
		Private _Estado_W As WhereParameter = Nothing
		Private _FechaR_W As WhereParameter = Nothing
		Private _IdUserR_W As WhereParameter = Nothing
		Private _Activo_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdEstBuzonInterno_W = Nothing
			_Estado_W = Nothing
			_FechaR_W = Nothing
			_IdUserR_W = Nothing
			_Activo_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdEstBuzonInterno() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdEstBuzonInterno, Parameters.IdEstBuzonInterno)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Estado() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Estado, Parameters.Estado)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaR, Parameters.FechaR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdUserR, Parameters.IdUserR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Activo, Parameters.Activo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdEstBuzonInterno() As AggregateParameter 
			Get
				If _IdEstBuzonInterno_W Is Nothing Then
					_IdEstBuzonInterno_W = TearOff.IdEstBuzonInterno
				End If
				Return _IdEstBuzonInterno_W
			End Get
		End Property

		Public ReadOnly Property Estado() As AggregateParameter 
			Get
				If _Estado_W Is Nothing Then
					_Estado_W = TearOff.Estado
				End If
				Return _Estado_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Private _IdEstBuzonInterno_W As AggregateParameter = Nothing
		Private _Estado_W As AggregateParameter = Nothing
		Private _FechaR_W As AggregateParameter = Nothing
		Private _IdUserR_W As AggregateParameter = Nothing
		Private _Activo_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdEstBuzonInterno_W = Nothing
		_Estado_W = Nothing
		_FechaR_W = Nothing
		_IdUserR_W = Nothing
		_Activo_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_EstadoBuzonInternoInsert]" 
	    
		CreateParameters(cmd)
		
		Dim p As SqlParameter
		p = cmd.Parameters(Parameters.IdEstBuzonInterno.ParameterName)
		p.Direction = ParameterDirection.Output
    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_EstadoBuzonInternoUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_EstadoBuzonInternoDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdEstBuzonInterno)
		p.SourceColumn = ColumnNames.IdEstBuzonInterno
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdEstBuzonInterno)
		p.SourceColumn = ColumnNames.IdEstBuzonInterno
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Estado)
		p.SourceColumn = ColumnNames.Estado
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaR)
		p.SourceColumn = ColumnNames.FechaR
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdUserR)
		p.SourceColumn = ColumnNames.IdUserR
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Activo)
		p.SourceColumn = ColumnNames.Activo
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

