Imports MyGeneration.dOOdads
Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.9)

Public Class EstadoBuzonInterno 
	Inherits _EstadoBuzonInterno

    Private sEstado As String
    Private sFechaR As String
    Private sIdUserR As String
    Private sActivo As String
    Public Property pActivo() As String
        Get
            Return sActivo
        End Get
        Set(ByVal value As String)
            sActivo = value
        End Set
    End Property

    Public Property pIdUserR() As String
        Get
            Return sIdUserR
        End Get
        Set(ByVal value As String)
            sIdUserR = value
        End Set
    End Property

    Public Property pFechaR() As String
        Get
            Return sFechaR
        End Get
        Set(ByVal value As String)
            sFechaR = value
        End Set
    End Property

    Public Property pEstado() As String
        Get
            Return sEstado
        End Get
        Set(ByVal value As String)
            sEstado = value
        End Set
    End Property
    Function obtEstDocInt(ByVal sIdEstDocInt As Integer) As Boolean
        Try
            If LoadByPrimaryKey(sIdEstDocInt) Then
                pActivo = Activo
                pEstado = Estado
                pFechaR = FechaR
                pIdUserR = IdUserR
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Function
End Class
