Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Personal 
    Inherits _Personal
    Dim sNomCargo As String
    Dim sNomArea As String
    Dim Cargos As New CapaLogicaNegocio.Cargos
    Dim Areas As New CapaLogicaNegocio.Areas
    Public ReadOnly Property NombreCargo()
        Get
            Return sNomCargo
        End Get
    End Property
    Public ReadOnly Property NombreArea()
        Get
            Return sNomArea
        End Get
    End Property
    Public Function obtCargoPersonal(ByVal sIdpersona As String)
        Dim sIdCargo As String
        Dim sIdArea As String
        If EobtCargo_Area(sIdpersona) Then
            sIdCargo = Me.IdCargo
            sIdArea = Me.IdArea
            sNomCargo = Cargos.EC_obtCargo(sIdCargo)
            sNomArea = Areas.EC_obtArea(sIdArea)
            Return True
        Else
            Return False
        End If
    End Function
    'Public Function obtAreaPersonal(ByVal sIdpersona As String)
    '    Dim sIdArea As String
    '    If EobtCargo_Area(sIdpersona) Then
    '        sIdArea = Me.IdArea
    '        sNomArea = Areas.EC_obtArea(sIdArea)
    '        Return True
    '    Else
    '        Return False
    '    End If
    'End Function
End Class
