Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class PersonNat 
	Inherits _PersonNat
    Public Function ListarPersonas(ByVal txtBusq As String) As DataTable
        Dim dt As DataTable
        'Me.Where.Tear()
        dt = Me.BuscaPersonNat(txtBusq)
        'dcoll.Add(dt, "Tabla")
        'dcoll.Add(rs, "NombreCol")
        Return dt
    End Function
End Class
