
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public Class Personal_Cargo_Areas
	Inherits  SqlClientEntity
	
		Public Sub New() 
			Me.QuerySource = "Personal_Cargo_Areas"
			Me.MappingName = "Personal_Cargo_Areas"
		End Sub

	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
    	Return MyBase.Query.Load()
	End Function
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub	

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdPersona As SqlParameter
			Get
				Return New SqlParameter("IdPersona", SqlDbType.Char, 7)
			End Get
		End Property
		
		Public Shared ReadOnly Property Cargo As SqlParameter
			Get
				Return New SqlParameter("Cargo", SqlDbType.VarChar, 40)
			End Get
		End Property
		
		Public Shared ReadOnly Property Area As SqlParameter
			Get
				Return New SqlParameter("Area", SqlDbType.VarChar, 40)
			End Get
		End Property
		
		Public Shared ReadOnly Property Activo As SqlParameter
			Get
				Return New SqlParameter("Activo", SqlDbType.Char, 1)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdPersona As String = "IdPersona"
        Public Const Cargo As String = "Cargo"
        Public Const Area As String = "Area"
        Public Const Activo As String = "Activo"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdPersona) = Personal_Cargo_Areas.PropertyNames.IdPersona
				ht(Cargo) = Personal_Cargo_Areas.PropertyNames.Cargo
				ht(Area) = Personal_Cargo_Areas.PropertyNames.Area
				ht(Activo) = Personal_Cargo_Areas.PropertyNames.Activo

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdPersona As String = "IdPersona"
        Public Const Cargo As String = "Cargo"
        Public Const Area As String = "Area"
        Public Const Activo As String = "Activo"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdPersona) = Personal_Cargo_Areas.ColumnNames.IdPersona
				ht(Cargo) = Personal_Cargo_Areas.ColumnNames.Cargo
				ht(Area) = Personal_Cargo_Areas.ColumnNames.Area
				ht(Activo) = Personal_Cargo_Areas.ColumnNames.Activo

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdPersona As String = "s_IdPersona"
        Public Const Cargo As String = "s_Cargo"
        Public Const Area As String = "s_Area"
        Public Const Activo As String = "s_Activo"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property IdPersona As String
			Get
				Return MyBase.GetString(ColumnNames.IdPersona)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.IdPersona, Value)
			End Set
		End Property

		Public Overridable Property Cargo As String
			Get
				Return MyBase.GetString(ColumnNames.Cargo)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Cargo, Value)
			End Set
		End Property

		Public Overridable Property Area As String
			Get
				Return MyBase.GetString(ColumnNames.Area)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Area, Value)
			End Set
		End Property

		Public Overridable Property Activo As String
			Get
				Return MyBase.GetString(ColumnNames.Activo)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Activo, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdPersona As String
			Get
				If Me.IsColumnNull(ColumnNames.IdPersona) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.IdPersona)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdPersona)
				Else
					Me.IdPersona = MyBase.SetStringAsString(ColumnNames.IdPersona, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Cargo As String
			Get
				If Me.IsColumnNull(ColumnNames.Cargo) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Cargo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Cargo)
				Else
					Me.Cargo = MyBase.SetStringAsString(ColumnNames.Cargo, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Area As String
			Get
				If Me.IsColumnNull(ColumnNames.Area) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Area)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Area)
				Else
					Me.Area = MyBase.SetStringAsString(ColumnNames.Area, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Activo As String
			Get
				If Me.IsColumnNull(ColumnNames.Activo) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Activo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Activo)
				Else
					Me.Activo = MyBase.SetStringAsString(ColumnNames.Activo, Value)
				End If
			End Set
		End Property


	#End Region 

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdPersona() As WhereParameter
			Get
				Dim where As WhereParameter = New WhereParameter(ColumnNames.IdPersona, Parameters.IdPersona)
				Me._clause._entity.Query.AddWhereParemeter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Cargo() As WhereParameter
			Get
				Dim where As WhereParameter = New WhereParameter(ColumnNames.Cargo, Parameters.Cargo)
				Me._clause._entity.Query.AddWhereParemeter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Area() As WhereParameter
			Get
				Dim where As WhereParameter = New WhereParameter(ColumnNames.Area, Parameters.Area)
				Me._clause._entity.Query.AddWhereParemeter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Activo() As WhereParameter
			Get
				Dim where As WhereParameter = New WhereParameter(ColumnNames.Activo, Parameters.Activo)
				Me._clause._entity.Query.AddWhereParemeter(where)
				Return where
			End Get
		End Property


		Private _clause as WhereClause
	End Class
	#End Region	

		Public ReadOnly Property IdPersona() As WhereParameter 
			Get
				If _IdPersona_W Is Nothing Then
					_IdPersona_W = TearOff.IdPersona
				End If
				Return _IdPersona_W
			End Get
		End Property

		Public ReadOnly Property Cargo() As WhereParameter 
			Get
				If _Cargo_W Is Nothing Then
					_Cargo_W = TearOff.Cargo
				End If
				Return _Cargo_W
			End Get
		End Property

		Public ReadOnly Property Area() As WhereParameter 
			Get
				If _Area_W Is Nothing Then
					_Area_W = TearOff.Area
				End If
				Return _Area_W
			End Get
		End Property

		Public ReadOnly Property Activo() As WhereParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Private _IdPersona_W As WhereParameter = Nothing
		Private _Cargo_W As WhereParameter = Nothing
		Private _Area_W As WhereParameter = Nothing
		Private _Activo_W As WhereParameter = Nothing

		Public Sub WhereClauseReset()

		_IdPersona_W = Nothing
		_Cargo_W = Nothing
		_Area_W = Nothing
		_Activo_W = Nothing
			Me._entity.Query.FlushWhereParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdPersona() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdPersona, Parameters.IdPersona)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Cargo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Cargo, Parameters.Cargo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Area() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Area, Parameters.Area)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Activo, Parameters.Activo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdPersona() As AggregateParameter 
			Get
				If _IdPersona_W Is Nothing Then
					_IdPersona_W = TearOff.IdPersona
				End If
				Return _IdPersona_W
			End Get
		End Property

		Public ReadOnly Property Cargo() As AggregateParameter 
			Get
				If _Cargo_W Is Nothing Then
					_Cargo_W = TearOff.Cargo
				End If
				Return _Cargo_W
			End Get
		End Property

		Public ReadOnly Property Area() As AggregateParameter 
			Get
				If _Area_W Is Nothing Then
					_Area_W = TearOff.Area
				End If
				Return _Area_W
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Private _IdPersona_W As AggregateParameter = Nothing
		Private _Cargo_W As AggregateParameter = Nothing
		Private _Area_W As AggregateParameter = Nothing
		Private _Activo_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdPersona_W = Nothing
		_Cargo_W = Nothing
		_Area_W = Nothing
		_Activo_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
		Return Nothing
	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
		Return Nothing
	End Function
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
		Return Nothing
	End Function
	
End Class

