Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.3)

Public Class TipoDocumento 
	Inherits _TipoDocumento
    Public Sub EC_insTipDoc(ByVal sDescripcion As String, ByVal sIduserR As String, ByVal sFecPror As String)
        AddNew()
        Descripcion = sDescripcion
        IdUserR = sIduserR
        FechaR = CType(sFecPror, Date)
        Save()
    End Sub
End Class
