Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.3)

Public Class TipoDocumento 
    Inherits _TipoDocumento
    Private dtTipDoc As DataTable
    Private sDescripcion As String
    Private sFechaR As String
    Private sIdUserR As String
    Public Property pIdUserR() As String
        Get
            Return sIdUserR
        End Get
        Set(ByVal value As String)
            sIdUserR = value
        End Set
    End Property

    Public Property pFechaR() As String
        Get
            Return sFechaR
        End Get
        Set(ByVal value As String)
            sFechaR = value
        End Set
    End Property

    Public Property pDescripcion() As String
        Get
            Return sDescripcion
        End Get
        Set(ByVal value As String)
            sDescripcion = value
        End Set
    End Property

    Public Property lsTipoDoc() As DataTable
        Get
            Return dtTipDoc
        End Get
        Set(ByVal value As DataTable)
            dtTipDoc = value
        End Set
    End Property

    Public Sub EC_insTipDoc(ByVal sDescripcion As String, ByVal sIduserR As String, ByVal sFecPror As String)
        AddNew()
        Descripcion = sDescripcion
        IdUserR = sIduserR
        FechaR = CType(sFecPror, Date)
        Save()
    End Sub
    Public Function EC_ListarTipoDoc() As Boolean
        If LoadAll() Then
            dtTipDoc = Me.DataTable
            Return True
        Else
            Return False
        End If
    End Function
    Public Function EC_ListarDocMenosReq() As Boolean
        Where.Descripcion.Value = "%Requerimiento%"
        Where.Descripcion.Operator = WhereParameter.Operand.NotLike

        If Query.Load() Then
            dtTipDoc = Me.DataTable
            Return True
        Else
            Return False
        End If
    End Function
    Public Function obtTipoDocumento(ByVal sIdTipDoc As Integer) As Boolean
        Try
            If LoadByPrimaryKey(sIdTipDoc) Then
                pDescripcion = Descripcion
                pIdUserR = IdUserR
                pFechaR = s_FechaR
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Throw ex
        End Try

    End Function
End Class
