Imports Microsoft.VisualBasic
Imports CapaAccesoDatos._Usuarios
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Usuarios 
    Inherits CapaAccesoDatos._Usuarios
    'Dim oUsuario As New Usuarios

    Public Function ListarDepartment() As String
        Dim rs As String
        rs = Me.s_IdPersona
        Return rs
    End Function
End Class
