
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.3)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _NivelAcceso
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "NivelAcceso"
			Me.MappingName = "NivelAcceso"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_NivelAccesoLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
	Public Overridable Function LoadByPrimaryKey(ByVal IdNivelAcceso As String) As Boolean

		Dim parameters As ListDictionary = New ListDictionary()
		parameters.Add(_NivelAcceso.Parameters.IdNivelAcceso, IdNivelAcceso)

		
		Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_NivelAccesoLoadByPrimaryKey]", parameters)

	End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdNivelAcceso As SqlParameter
			Get
				Return New SqlParameter("@IdNivelAcceso", SqlDbType.Char, 3)
			End Get
		End Property
		
		Public Shared ReadOnly Property Descripcion As SqlParameter
			Get
				Return New SqlParameter("@Descripcion", SqlDbType.NChar, 20)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdNivelAcceso As String = "IdNivelAcceso"
        Public Const Descripcion As String = "Descripcion"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdNivelAcceso) = _NivelAcceso.PropertyNames.IdNivelAcceso
				ht(Descripcion) = _NivelAcceso.PropertyNames.Descripcion

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdNivelAcceso As String = "IdNivelAcceso"
        Public Const Descripcion As String = "Descripcion"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdNivelAcceso) = _NivelAcceso.ColumnNames.IdNivelAcceso
				ht(Descripcion) = _NivelAcceso.ColumnNames.Descripcion

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdNivelAcceso As String = "s_IdNivelAcceso"
        Public Const Descripcion As String = "s_Descripcion"

	End Class
	#End Region		
	
	#Region "Properties" 
		Public Overridable Property IdNivelAcceso As String
			Get
				Return MyBase.GetString(ColumnNames.IdNivelAcceso)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.IdNivelAcceso, Value)
			End Set
		End Property

		Public Overridable Property Descripcion As String
			Get
				Return MyBase.GetString(ColumnNames.Descripcion)
			End Get
			Set(ByVal Value As String)
				MyBase.SetString(ColumnNames.Descripcion, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdNivelAcceso As String
			Get
				If Me.IsColumnNull(ColumnNames.IdNivelAcceso) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.IdNivelAcceso)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdNivelAcceso)
				Else
					Me.IdNivelAcceso = MyBase.SetStringAsString(ColumnNames.IdNivelAcceso, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Descripcion As String
			Get
				If Me.IsColumnNull(ColumnNames.Descripcion) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ColumnNames.Descripcion)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Descripcion)
				Else
					Me.Descripcion = MyBase.SetStringAsString(ColumnNames.Descripcion, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdNivelAcceso() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdNivelAcceso, Parameters.IdNivelAcceso)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Descripcion() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Descripcion, Parameters.Descripcion)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdNivelAcceso() As WhereParameter 
			Get
				If _IdNivelAcceso_W Is Nothing Then
					_IdNivelAcceso_W = TearOff.IdNivelAcceso
				End If
				Return _IdNivelAcceso_W
			End Get
		End Property

		Public ReadOnly Property Descripcion() As WhereParameter 
			Get
				If _Descripcion_W Is Nothing Then
					_Descripcion_W = TearOff.Descripcion
				End If
				Return _Descripcion_W
			End Get
		End Property

		Private _IdNivelAcceso_W As WhereParameter = Nothing
		Private _Descripcion_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdNivelAcceso_W = Nothing
			_Descripcion_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdNivelAcceso() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdNivelAcceso, Parameters.IdNivelAcceso)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Descripcion() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Descripcion, Parameters.Descripcion)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdNivelAcceso() As AggregateParameter 
			Get
				If _IdNivelAcceso_W Is Nothing Then
					_IdNivelAcceso_W = TearOff.IdNivelAcceso
				End If
				Return _IdNivelAcceso_W
			End Get
		End Property

		Public ReadOnly Property Descripcion() As AggregateParameter 
			Get
				If _Descripcion_W Is Nothing Then
					_Descripcion_W = TearOff.Descripcion
				End If
				Return _Descripcion_W
			End Get
		End Property

		Private _IdNivelAcceso_W As AggregateParameter = Nothing
		Private _Descripcion_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdNivelAcceso_W = Nothing
		_Descripcion_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_NivelAccesoInsert]" 
	    
		CreateParameters(cmd)
		    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_NivelAccesoUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_NivelAccesoDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdNivelAcceso)
		p.SourceColumn = ColumnNames.IdNivelAcceso
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdNivelAcceso)
		p.SourceColumn = ColumnNames.IdNivelAcceso
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Descripcion)
		p.SourceColumn = ColumnNames.Descripcion
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

