
'===============================================================================
'  Generated From - VbNet_SQL_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  **
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can Override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject
'    Inherits _YourObject
'
'  End Class
'
'===============================================================================

' Generated by MyGeneration Version # (1.3.0.9)

Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Collections
Imports System.Collections.Specialized

Imports MyGeneration.dOOdads

Public MustInherit Class _TipoDocumentoxAreasxAgencia
	Inherits SqlClientEntity

		Public Sub New() 
			Me.QuerySource = "TipoDocumentoxAreasxAgencia"
			Me.MappingName = "TipoDocumentoxAreasxAgencia"
		End Sub

	'=================================================================
	'  Public Overrides Sub AddNew()
	'=================================================================
	'
	'=================================================================
	Public Overrides Sub AddNew()
		MyBase.AddNew()
				
	End Sub
	
	Public Overrides Sub FlushData()
		Me._whereClause = nothing
		Me._aggregateClause = nothing		
		MyBase.FlushData()
	End Sub
	
		
	'=================================================================
	'  	Public Function LoadAll() As Boolean
	'=================================================================
	'  Loads all of the records in the database, and sets the currentRow to the first row
	'=================================================================
	Public Function LoadAll() As Boolean
	
		Dim parameters As ListDictionary = Nothing
		
		
    	Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_TipoDocumentoxAreasxAgenciaLoadAll]", parameters)
		
	End Function

	'=================================================================
	' Public Overridable Function LoadByPrimaryKey()  As Boolean
	'=================================================================
	'  Loads a single row of via the primary key
	'=================================================================
    Public Overridable Function LoadByPrimaryKey(ByVal IdTipoDocumento As Integer, ByVal IdArea As String, ByVal IdAgencia As String) As Boolean

        Dim parameters As ListDictionary = New ListDictionary()
        parameters.Add(_TipoDocumentoxAreasxAgencia.Parameters.IdTipoDocumento, IdTipoDocumento)

        parameters.Add(_TipoDocumentoxAreasxAgencia.Parameters.IdArea, IdArea)

        parameters.Add(_TipoDocumentoxAreasxAgencia.Parameters.IdAgencia, IdAgencia)


        Return MyBase.LoadFromSql("[" + Me.SchemaStoredProcedure + "proc_TipoDocumentoxAreasxAgenciaLoadByPrimaryKey]", parameters)

    End Function

	#Region "Parameters"
	Protected class Parameters 
		
		Public Shared ReadOnly Property IdTipoDocumento As SqlParameter
			Get
				Return New SqlParameter("@IdTipoDocumento", SqlDbType.Int, 0)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdArea As SqlParameter
			Get
				Return New SqlParameter("@IdArea", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdAgencia As SqlParameter
			Get
				Return New SqlParameter("@IdAgencia", SqlDbType.Char, 2)
			End Get
		End Property
		
		Public Shared ReadOnly Property Activo As SqlParameter
			Get
				Return New SqlParameter("@Activo", SqlDbType.Char, 1)
			End Get
		End Property
		
		Public Shared ReadOnly Property IdUserR As SqlParameter
			Get
				Return New SqlParameter("@IdUserR", SqlDbType.Char, 6)
			End Get
		End Property
		
		Public Shared ReadOnly Property FechaR As SqlParameter
			Get
				Return New SqlParameter("@FechaR", SqlDbType.DateTime, 0)
			End Get
		End Property
		
	End Class
	#End Region	

	#Region "ColumnNames"
	Public class ColumnNames
		
        Public Const IdTipoDocumento As String = "IdTipoDocumento"
        Public Const IdArea As String = "IdArea"
        Public Const IdAgencia As String = "IdAgencia"
        Public Const Activo As String = "Activo"
        Public Const IdUserR As String = "IdUserR"
        Public Const FechaR As String = "FechaR"

		Shared Public Function ToPropertyName(ByVal columnName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdTipoDocumento) = _TipoDocumentoxAreasxAgencia.PropertyNames.IdTipoDocumento
				ht(IdArea) = _TipoDocumentoxAreasxAgencia.PropertyNames.IdArea
				ht(IdAgencia) = _TipoDocumentoxAreasxAgencia.PropertyNames.IdAgencia
				ht(Activo) = _TipoDocumentoxAreasxAgencia.PropertyNames.Activo
				ht(IdUserR) = _TipoDocumentoxAreasxAgencia.PropertyNames.IdUserR
				ht(FechaR) = _TipoDocumentoxAreasxAgencia.PropertyNames.FechaR

			End If
			
			Return CType(ht(columnName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing		 
	End Class
	#End Region	
	
	#Region "PropertyNames"
	Public class PropertyNames
		
        Public Const IdTipoDocumento As String = "IdTipoDocumento"
        Public Const IdArea As String = "IdArea"
        Public Const IdAgencia As String = "IdAgencia"
        Public Const Activo As String = "Activo"
        Public Const IdUserR As String = "IdUserR"
        Public Const FechaR As String = "FechaR"

		Shared Public Function ToColumnName(ByVal propertyName As String) As String

			If ht Is Nothing Then
			
				ht = new Hashtable
				
				ht(IdTipoDocumento) = _TipoDocumentoxAreasxAgencia.ColumnNames.IdTipoDocumento
				ht(IdArea) = _TipoDocumentoxAreasxAgencia.ColumnNames.IdArea
				ht(IdAgencia) = _TipoDocumentoxAreasxAgencia.ColumnNames.IdAgencia
				ht(Activo) = _TipoDocumentoxAreasxAgencia.ColumnNames.Activo
				ht(IdUserR) = _TipoDocumentoxAreasxAgencia.ColumnNames.IdUserR
				ht(FechaR) = _TipoDocumentoxAreasxAgencia.ColumnNames.FechaR

			End If
			
			Return CType(ht(propertyName), String)
			
		End Function
		
		Shared Private ht  As Hashtable = Nothing
		
	End Class
	#End Region	
	
	#Region "StringPropertyNames"
	Public class StringPropertyNames
		
        Public Const IdTipoDocumento As String = "s_IdTipoDocumento"
        Public Const IdArea As String = "s_IdArea"
        Public Const IdAgencia As String = "s_IdAgencia"
        Public Const Activo As String = "s_Activo"
        Public Const IdUserR As String = "s_IdUserR"
        Public Const FechaR As String = "s_FechaR"

	End Class
	#End Region		
	
	#Region "Properties" 
    Public Overridable Property IdTipoDocumento() As Integer
        Get
            Return MyBase.GetInteger(ColumnNames.IdTipoDocumento)
        End Get
        Set(ByVal Value As Integer)
            MyBase.SetInteger(ColumnNames.IdTipoDocumento, Value)
        End Set
    End Property

		Public Overridable Property IdArea As string
			Get
				Return MyBase.Getstring(ColumnNames.IdArea)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdArea, Value)
			End Set
		End Property

		Public Overridable Property IdAgencia As string
			Get
				Return MyBase.Getstring(ColumnNames.IdAgencia)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdAgencia, Value)
			End Set
		End Property

		Public Overridable Property Activo As string
			Get
				Return MyBase.Getstring(ColumnNames.Activo)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.Activo, Value)
			End Set
		End Property

		Public Overridable Property IdUserR As string
			Get
				Return MyBase.Getstring(ColumnNames.IdUserR)
			End Get
			Set(ByVal Value As string)
				MyBase.Setstring(ColumnNames.IdUserR, Value)
			End Set
		End Property

		Public Overridable Property FechaR As DateTime
			Get
				Return MyBase.GetDateTime(ColumnNames.FechaR)
			End Get
			Set(ByVal Value As DateTime)
				MyBase.SetDateTime(ColumnNames.FechaR, Value)
			End Set
		End Property


	#End Region  
	
	#Region "String Properties" 

		Public Overridable Property s_IdTipoDocumento As String
			Get
				If Me.IsColumnNull(ColumnNames.IdTipoDocumento) Then
					Return String.Empty
				Else
                Return MyBase.GetIntegerAsString(ColumnNames.IdTipoDocumento)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdTipoDocumento)
				Else
                Me.IdTipoDocumento = MyBase.SetIntegerAsString(ColumnNames.IdTipoDocumento, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdArea As String
			Get
				If Me.IsColumnNull(ColumnNames.IdArea) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdArea)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdArea)
				Else
					Me.IdArea = MyBase.SetstringAsString(ColumnNames.IdArea, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdAgencia As String
			Get
				If Me.IsColumnNull(ColumnNames.IdAgencia) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdAgencia)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdAgencia)
				Else
					Me.IdAgencia = MyBase.SetstringAsString(ColumnNames.IdAgencia, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Activo As String
			Get
				If Me.IsColumnNull(ColumnNames.Activo) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.Activo)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.Activo)
				Else
					Me.Activo = MyBase.SetstringAsString(ColumnNames.Activo, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_IdUserR As String
			Get
				If Me.IsColumnNull(ColumnNames.IdUserR) Then
					Return String.Empty
				Else
					Return MyBase.GetstringAsString(ColumnNames.IdUserR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.IdUserR)
				Else
					Me.IdUserR = MyBase.SetstringAsString(ColumnNames.IdUserR, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_FechaR As String
			Get
				If Me.IsColumnNull(ColumnNames.FechaR) Then
					Return String.Empty
				Else
					Return MyBase.GetDateTimeAsString(ColumnNames.FechaR)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ColumnNames.FechaR)
				Else
					Me.FechaR = MyBase.SetDateTimeAsString(ColumnNames.FechaR, Value)
				End If
			End Set
		End Property


	#End Region  	

	#Region "Where Clause"
    Public Class WhereClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "TearOff's"
		Public class TearOffWhereParameter

			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub
		
	
			Public ReadOnly Property IdTipoDocumento() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdTipoDocumento, Parameters.IdTipoDocumento)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdArea() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdArea, Parameters.IdArea)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdAgencia() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdAgencia, Parameters.IdAgencia)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property Activo() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.Activo, Parameters.Activo)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property IdUserR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.IdUserR, Parameters.IdUserR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property

			Public ReadOnly Property FechaR() As WhereParameter
				Get
					Dim where As WhereParameter = New WhereParameter(ColumnNames.FechaR, Parameters.FechaR)
					Me._clause._entity.Query.AddWhereParemeter(where)
					Return where
				End Get
			End Property


			Private _clause as WhereClause
		End Class
		#End Region	

		Public ReadOnly Property IdTipoDocumento() As WhereParameter 
			Get
				If _IdTipoDocumento_W Is Nothing Then
					_IdTipoDocumento_W = TearOff.IdTipoDocumento
				End If
				Return _IdTipoDocumento_W
			End Get
		End Property

		Public ReadOnly Property IdArea() As WhereParameter 
			Get
				If _IdArea_W Is Nothing Then
					_IdArea_W = TearOff.IdArea
				End If
				Return _IdArea_W
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As WhereParameter 
			Get
				If _IdAgencia_W Is Nothing Then
					_IdAgencia_W = TearOff.IdAgencia
				End If
				Return _IdAgencia_W
			End Get
		End Property

		Public ReadOnly Property Activo() As WhereParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As WhereParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As WhereParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Private _IdTipoDocumento_W As WhereParameter = Nothing
		Private _IdArea_W As WhereParameter = Nothing
		Private _IdAgencia_W As WhereParameter = Nothing
		Private _Activo_W As WhereParameter = Nothing
		Private _IdUserR_W As WhereParameter = Nothing
		Private _FechaR_W As WhereParameter = Nothing

			Public Sub WhereClauseReset()

			_IdTipoDocumento_W = Nothing
			_IdArea_W = Nothing
			_IdAgencia_W = Nothing
			_Activo_W = Nothing
			_IdUserR_W = Nothing
			_FechaR_W = Nothing
				Me._entity.Query.FlushWhereParameters()

			End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region "Aggregate Clause"
    Public Class AggregateClause

        Public Sub New(ByVal entity As BusinessEntity)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region "AggregateParameter TearOff's"
		Public class TearOffAggregateParameter

			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub
		
	
		Public ReadOnly Property IdTipoDocumento() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdTipoDocumento, Parameters.IdTipoDocumento)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdArea() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdArea, Parameters.IdArea)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdAgencia, Parameters.IdAgencia)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.Activo, Parameters.Activo)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.IdUserR, Parameters.IdUserR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter
			Get
				Dim where As AggregateParameter = New AggregateParameter(ColumnNames.FechaR, Parameters.FechaR)
				Me._clause._entity.Query.AddAggregateParameter(where)
				Return where
			End Get
		End Property


			Private _clause as AggregateClause
		End Class
		#End Region	

		Public ReadOnly Property IdTipoDocumento() As AggregateParameter 
			Get
				If _IdTipoDocumento_W Is Nothing Then
					_IdTipoDocumento_W = TearOff.IdTipoDocumento
				End If
				Return _IdTipoDocumento_W
			End Get
		End Property

		Public ReadOnly Property IdArea() As AggregateParameter 
			Get
				If _IdArea_W Is Nothing Then
					_IdArea_W = TearOff.IdArea
				End If
				Return _IdArea_W
			End Get
		End Property

		Public ReadOnly Property IdAgencia() As AggregateParameter 
			Get
				If _IdAgencia_W Is Nothing Then
					_IdAgencia_W = TearOff.IdAgencia
				End If
				Return _IdAgencia_W
			End Get
		End Property

		Public ReadOnly Property Activo() As AggregateParameter 
			Get
				If _Activo_W Is Nothing Then
					_Activo_W = TearOff.Activo
				End If
				Return _Activo_W
			End Get
		End Property

		Public ReadOnly Property IdUserR() As AggregateParameter 
			Get
				If _IdUserR_W Is Nothing Then
					_IdUserR_W = TearOff.IdUserR
				End If
				Return _IdUserR_W
			End Get
		End Property

		Public ReadOnly Property FechaR() As AggregateParameter 
			Get
				If _FechaR_W Is Nothing Then
					_FechaR_W = TearOff.FechaR
				End If
				Return _FechaR_W
			End Get
		End Property

		Private _IdTipoDocumento_W As AggregateParameter = Nothing
		Private _IdArea_W As AggregateParameter = Nothing
		Private _IdAgencia_W As AggregateParameter = Nothing
		Private _Activo_W As AggregateParameter = Nothing
		Private _IdUserR_W As AggregateParameter = Nothing
		Private _FechaR_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_IdTipoDocumento_W = Nothing
		_IdArea_W = Nothing
		_IdAgencia_W = Nothing
		_Activo_W = Nothing
		_IdUserR_W = Nothing
		_FechaR_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As BusinessEntity
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

	Protected Overrides Function GetInsertCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_TipoDocumentoxAreasxAgenciaInsert]" 
	    
		CreateParameters(cmd)
		    
		Return cmd 

  	End Function
	
	Protected Overrides Function GetUpdateCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_TipoDocumentoxAreasxAgenciaUpdate]" 
		
		CreateParameters(cmd) 
		    
		Return cmd
	
	End Function	
	
	Protected Overrides Function GetDeleteCommand() As IDbCommand
	
		Dim cmd As SqlCommand = New SqlCommand
		cmd.CommandType = CommandType.StoredProcedure    
		cmd.CommandText = "[" + Me.SchemaStoredProcedure + "proc_TipoDocumentoxAreasxAgenciaDelete]" 
		
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdTipoDocumento)
		p.SourceColumn = ColumnNames.IdTipoDocumento
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdArea)
		p.SourceColumn = ColumnNames.IdArea
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdAgencia)
		p.SourceColumn = ColumnNames.IdAgencia
		p.SourceVersion = DataRowVersion.Current

  
		Return cmd
	
	End Function	
	
	Private Sub CreateParameters(ByVal cmd As SqlCommand)
	
		Dim p As SqlParameter
		p = cmd.Parameters.Add(Parameters.IdTipoDocumento)
		p.SourceColumn = ColumnNames.IdTipoDocumento
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdArea)
		p.SourceColumn = ColumnNames.IdArea
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdAgencia)
		p.SourceColumn = ColumnNames.IdAgencia
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.Activo)
		p.SourceColumn = ColumnNames.Activo
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.IdUserR)
		p.SourceColumn = ColumnNames.IdUserR
		p.SourceVersion = DataRowVersion.Current

		p = cmd.Parameters.Add(Parameters.FechaR)
		p.SourceColumn = ColumnNames.FechaR
		p.SourceVersion = DataRowVersion.Current


	End Sub	

End Class

