Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Agencias 
    Inherits _Agencias

    Private dtAgencia As DataTable
    Public Property lsAgencia() As DataTable
        Get
            Return dtAgencia
        End Get
        Set(ByVal value As DataTable)
            dtAgencia = value
        End Set
    End Property

    Public Function EC_obtAgencia(ByVal sEIdAgencia As String) As String
        If LoadByPrimaryKey(sEIdAgencia) Then
            Return Me.Agencia
        Else
            Return False
        End If
    End Function
    Public Function EC_listaAgencias() As Boolean
        If LoadAll() Then
            dtAgencia = Me.DataTable
            Return True
        Else
            Return False
        End If
    End Function
End Class
