Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.3)

Public Class AsignaDocInterno 
    Inherits _AsignaDocInterno
    Private EC_IdUSer As String
    Private EC_IdDocInterno As String
    Private EC_IdEstAsigDoc As String
    Private EC_Condicion As String
    Private EC_FechaR As String
    Private EC_IdUserR As String
    Public Property pIdEstAsigDoc() As String
        Get
            Return EC_IdEstAsigDoc
        End Get
        Set(ByVal value As String)
            EC_IdEstAsigDoc = value
        End Set
    End Property
    Public Property pCondicion() As String
        Get
            Return EC_Condicion
        End Get
        Set(ByVal value As String)
            EC_Condicion = value
        End Set
    End Property
    Public Property pFechaR() As String
        Get
            Return EC_FechaR
        End Get
        Set(ByVal value As String)
            EC_FechaR = value
        End Set
    End Property
    Public Property pIdUserR() As String
        Get
            Return EC_IdUserR
        End Get
        Set(ByVal value As String)
            EC_IdUserR = value
        End Set
    End Property
    Public Property pIdUser() As String
        Get
            Return EC_IdUSer
        End Get
        Set(ByVal value As String)
            EC_IdUSer = value
        End Set
    End Property
    Public Property pIdDocInterno() As String
        Get
            Return EC_IdDocInterno
        End Get
        Set(ByVal value As String)
            EC_IdDocInterno = value
        End Set
    End Property

    Public Sub EC_insertaAigDocInt()
        Dim tx As TransactionMgr
        tx = TransactionMgr.ThreadTransactionMgr()
        Try

            AddNew()
            IdDocInterno = EC_IdDocInterno
            IdUser = EC_IdUSer
            IdEstAsigDoc = EC_IdEstAsigDoc
            Condicion = EC_Condicion
            FechaR = EC_FechaR
            IdUserR = EC_IdUserR
            tx.BeginTransaction()
            Save()
            tx.CommitTransaction()
        Catch ex As Exception
            tx.RollbackTransaction()
            tx.ThreadTransactionMgrReset()
            Throw ex
        End Try

    End Sub


End Class
