Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.3)

Public Class Cargos 
    Inherits _Cargos
    Dim sECNomCargo As String

    Public Function EC_obtCargo(ByVal sEIdCargo As String) As String
        If EobtCargo(sEIdCargo) Then
            Return Me.Cargo
        Else
            Return " "
        End If
    End Function

End Class
