Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
' Generated by MyGeneration Version # (1.3.0.9)

Public Class CARGOSXAREAXAGENCIA 
    Inherits _CARGOSXAREAXAGENCIA
    Private sDescripcion As String
    Private sActivo As String
    Public Property pActivo() As String
        Get
            Return sActivo
        End Get
        Set(ByVal value As String)
            sActivo = value
        End Set
    End Property

    Public Property pDescripcion() As String
        Get
            Return sDescripcion
        End Get
        Set(ByVal value As String)
            sDescripcion = value
        End Set
    End Property
    Public Function obtCargosxAreaxAgencia(ByVal sidcargo As String, ByVal sidarea As String, ByVal sidagencia As String) As Boolean
        Try
            Where.IdCargo.Value = sidcargo
            Where.IdCargo.Operator = WhereParameter.Operand.Equal
            Where.IdArea.Value = sidarea
            Where.IdArea.Operator = WhereParameter.Operand.Equal
            Where.IdAgencia.Value = sidagencia
            Where.IdAgencia.Operator = WhereParameter.Operand.Equal
            If Query.Load Then
                pDescripcion = Denominacion
                pActivo = Activo
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Throw ex
        Finally
            Where.WhereClauseReset()
        End Try

       
    End Function
End Class
