Imports CapaAccesoDatos
Imports MyGeneration.dOOdads
Imports System.Collections.Specialized

' Generated by MyGeneration Version # (1.3.0.3)

Public Class PersonNat 
	Inherits _PersonNat
 
    Public Function ObtNombreCompleto(ByVal sIdPersona As String) As String
        Dim sNomComp As String
        If LoadByPrimaryKey(sIdPersona) Then
            sNomComp = ApePat + " " + ApeMat + " " + Nombres
            Return sNomComp
        Else
            Return " "
        End If
    End Function
    Public Function ListarPersonas(ByVal sCadena As String) As DataTable
        Dim Parms As ListDictionary = New ListDictionary
        Parms.Add("param", sCadena + "%")
        Parms.Add("campo", "[Apepat]")
        Parms.Add("tabla", "[PersonNat]")
        If (Me.LoadFromSql("paBuscador", Parms)) Then

        End If
        '--If (Me.Query.Load()) Then

        ' End If
        'Dim query1 = Me.Query.GenerateSQL
        Return Me.DataTable

    End Function
End Class
'Public Function ListarPersonas(ByVal txtBusq As String) As DataTable
'    Dim dt As DataTable
'    'Me.Where.Tear()
'    dt = Me.BuscaPersonNat(txtBusq)
'    'dcoll.Add(dt, "Tabla")
'    'dcoll.Add(rs, "NombreCol")
'    Return dt
'End Function