Imports MyGeneration.dOOdads
Imports CapaAccesoDatos
' Generated by MyGeneration Version # (1.3.0.9)

Public Class Tablas 
    Inherits _Tablas

    Private lsTabla As DataTable
    Public Property pLsTabla() As DataTable
        Get
            Return lsTabla
        End Get
        Set(ByVal value As DataTable)
            lsTabla = value
        End Set
    End Property

    Function obtTablaxIdTabla(ByVal nIdTabla As Integer) As Boolean
        Try
            Where.IdTabla.Value = nIdTabla
            Where.IdTabla.Operator = WhereParameter.Operand.Equal
            If Query.Load Then
                lsTabla = DataTable
                Return True
            Else
                Return False
            End If
        Catch ex As Exception
            Throw ex
        Finally
            Where.WhereClauseReset()
        End Try

    End Function

End Class
